version: '3.7'

volumes:
    builder-data: {}

services:
    builder:
        image: "ghcr.io/jolicode/monologue/builder:${BUILDER_VERSION:-latest}"
        build:
            context: services/php
            target: builder
            # cache_to:
            #     - "ghcr.io/jolicode/monologue/builder:${BUILDER_VERSION:-latest}"
            # cache_from:
            #     - "ghcr.io/jolicode/monologue/builder:${BUILDER_VERSION:-latest}"
        depends_on:
            - postgres
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - UID=${USER_ID}
            - GITHUB_ACTIONS
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            - "builder-data:/home/app"
