# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        http_client.transport:
            class: Symfony\Component\HttpClient\MockHttpClient
