name: Continuous Integration

'on':
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    schedule:
        - cron: '0 0 * * MON'

permissions:
    contents: read

jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-latest
        env:
            BUILDKIT_PROGRESS: plain
            CI: 1
        steps:
            -
                uses: actions/checkout@v3

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    tools: jolicode/castor

            -
                name: 'Build and start the infrastructure'
                run: castor start

            -
                name: 'Run PHP-CS-Fixer'
                run: castor qa:cs --dry-run

            -
                name: 'Run PHPStan'
                run: castor qa:phpstan

            -
                name: 'Run PHPUnit'
                run: castor qa:phpunit
